import { NextRequest, NextResponse } from "next/server";
import { verifyWebhookSignature } from "@/lib/github/webhooks";
import { createCheckRun, updateCheckRun } from "@/lib/github/checks";
import { getInstallationOctokit } from "@/lib/github/app";
import { createServerSupabaseClient } from "@/lib/supabase/server";
import { buildPRComment } from "@/lib/github/comments";
import { postCommitComment, buildDirectPushWarning } from "@/lib/github/commit-comments";
import { dispatchNotification } from "@/lib/github/notifications";
import { configureBranchProtection } from "@/lib/github/branch-protection";
import { runCheckPipeline } from "@lastgate/engine";
import type { ChangedFile, CommitInfo } from "@lastgate/engine";

export const dynamic = "force-dynamic";
export const maxDuration = 60; // Allow up to 60s for pipeline processing

async function fetchChangedFiles(
  octokit: Awaited<ReturnType<typeof getInstallationOctokit>>,
  owner: string,
  repo: string,
  sha: string
): Promise<ChangedFile[]> {
  try {
    const { data } = await octokit.request(
      "GET /repos/{owner}/{repo}/commits/{ref}",
      { owner, repo, ref: sha }
    );

    return (data.files || []).map((f: Record<string, unknown>) => ({
      path: f.filename as string,
      content: (f.patch as string) || "",
      patch: (f.patch as string) || "",
      status: mapGitHubStatus(f.status as string),
    }));
  } catch (error) {
    console.error("Failed to fetch changed files:", error);
    return [];
  }
}

function mapGitHubStatus(
  status: string
): "added" | "modified" | "removed" | "renamed" {
  switch (status) {
    case "added":
      return "added";
    case "removed":
      return "removed";
    case "renamed":
      return "renamed";
    default:
      return "modified";
  }
}

async function findOrCreateRepo(
  supabase: ReturnType<typeof createServerSupabaseClient>,
  repoFullName: string,
  installationId: number
) {
  // Try to find existing repo
  const { data: existing } = await supabase
    .from("repos")
    .select("id")
    .eq("full_name", repoFullName)
    .single();

  if (existing) return existing.id;

  // Create repo record
  const { data: created } = await supabase
    .from("repos")
    .insert({
      full_name: repoFullName,
      github_repo_id: 0, // Will be updated on next sync
      installation_id: installationId,
      default_branch: "main",
    })
    .select("id")
    .single();

  return created?.id || null;
}

function detectAgentCommit(message: string, author: string): boolean {
  const agentPatterns = [
    /\b(claude|copilot|cursor|aider|cody|devin|sweep)\b/i,
    /\bgenerated by\b/i,
    /\bauto-generated\b/i,
    /\bai-generated\b/i,
  ];
  const text = `${message} ${author}`;
  return agentPatterns.some((p) => p.test(text));
}

export async function POST(request: NextRequest) {
  try {
    const body = await request.text();
    const signature = request.headers.get("x-hub-signature-256");
    const event = request.headers.get("x-github-event");
    const deliveryId = request.headers.get("x-github-delivery");

    console.log(`[webhook] Received event="${event}" delivery="${deliveryId}" body_length=${body.length}`);

    if (!signature) {
      console.log("[webhook] Missing signature header");
      return NextResponse.json(
        { error: "Missing signature" },
        { status: 401 }
      );
    }

    const secret = process.env.GITHUB_WEBHOOK_SECRET?.trim();
    if (!secret) {
      console.error("[webhook] GITHUB_WEBHOOK_SECRET not set");
      return NextResponse.json(
        { error: "Webhook secret not configured" },
        { status: 500 }
      );
    }

    console.log(`[webhook] Secret length=${secret.length} sig_prefix=${signature.slice(0, 20)}`);

    const isValid = verifyWebhookSignature(body, signature, secret);
    if (!isValid) {
      console.log("[webhook] Invalid signature — secret mismatch");
      return NextResponse.json(
        { error: "Invalid signature" },
        { status: 401 }
      );
    }

    console.log(`[webhook] Signature valid, processing event="${event}"`);

    const payload = JSON.parse(body);
    const supabase = createServerSupabaseClient();

    if (event === "push" || event === "pull_request") {
      return await handleCheckEvent(event, payload, supabase);
    }

    console.log(`[webhook] Ignoring event="${event}"`);
    return NextResponse.json({ ok: true, event, action: "ignored" });
  } catch (error) {
    console.error("[webhook] Unhandled error:", error);
    return NextResponse.json(
      { error: "Internal server error" },
      { status: 500 }
    );
  }
}

async function handleCheckEvent(
  event: string,
  payload: Record<string, unknown>,
  supabase: ReturnType<typeof createServerSupabaseClient>
) {
  const installationId = (
    payload.installation as Record<string, unknown> | undefined
  )?.id as number | undefined;

  if (!installationId) {
    console.log("[webhook] No installation ID in payload");
    return NextResponse.json(
      { error: "No installation ID" },
      { status: 400 }
    );
  }

  console.log(`[webhook] installationId=${installationId}`);

  // Extract event-specific data
  const repository = payload.repository as Record<string, unknown>;
  const repoOwner = (repository.owner as Record<string, unknown>)
    .login as string;
  const repoName = repository.name as string;
  const repoFullName = repository.full_name as string;

  let headSha: string;
  let branch: string;
  let commitMessage: string;
  let commitAuthor: string;
  let prNumber: number | null = null;
  let triggerEvent: string;

  if (event === "push") {
    headSha = payload.after as string;
    branch = (payload.ref as string).replace("refs/heads/", "");
    const headCommit = payload.head_commit as Record<string, unknown> | null;
    commitMessage = (headCommit?.message as string) || "";
    commitAuthor = (payload.pusher as Record<string, unknown>).name as string;
    triggerEvent = "push";
  } else {
    const action = payload.action as string;
    if (action !== "opened" && action !== "synchronize") {
      return NextResponse.json({ ok: true, action: "ignored" });
    }
    const pr = payload.pull_request as Record<string, unknown>;
    const head = pr.head as Record<string, unknown>;
    headSha = head.sha as string;
    branch = head.ref as string;
    commitMessage = pr.title as string;
    commitAuthor = (pr.user as Record<string, unknown>).login as string;
    prNumber = pr.number as number;
    triggerEvent = "pull_request";
  }

  console.log(`[webhook] Processing ${event} for ${repoFullName} branch=${branch} sha=${headSha.slice(0, 8)}`);

  const octokit = await getInstallationOctokit(installationId);

  // Create a GitHub Check Run
  let checkRun;
  try {
    checkRun = await createCheckRun({
    installationId,
    owner: repoOwner,
    repo: repoName,
    headSha,
    name: "LastGate Pre-flight Check",
  });
    console.log(`[webhook] GitHub Check Run created id=${checkRun.id}`);
  } catch (err) {
    console.error("[webhook] Failed to create GitHub Check Run:", err);
    // Continue without GitHub Check Run — still store in Supabase
    checkRun = { id: 0 };
  }

  // Find or create repo record in Supabase
  const repoId = await findOrCreateRepo(supabase, repoFullName, installationId);
  console.log(`[webhook] repoId=${repoId}`);

  // Insert check_runs record
  const { data: checkRunRecord, error: insertError } = await supabase
    .from("check_runs")
    .insert({
      repo_id: repoId,
      commit_sha: headSha,
      pr_number: prNumber,
      branch,
      trigger_event: triggerEvent,
      status: "running",
      commit_message: commitMessage,
      commit_author: commitAuthor,
      is_agent_commit: detectAgentCommit(commitMessage, commitAuthor),
    })
    .select("id")
    .single();

  if (insertError) {
    console.error("[webhook] Failed to insert check_runs:", insertError);
  } else {
    console.log(`[webhook] check_runs record created id=${checkRunRecord?.id}`);
  }

  // Fetch changed files from GitHub
  const files = await fetchChangedFiles(octokit, repoOwner, repoName, headSha);
  console.log(`[webhook] Fetched ${files.length} changed files`);

  // Build commit info
  const commits: CommitInfo[] = [
    {
      sha: headSha,
      message: commitMessage,
      author: commitAuthor,
      timestamp: new Date().toISOString(),
    },
  ];

  // Fetch repo config if available
  let repoConfig = {};
  if (repoId) {
    const { data: repoData } = await supabase
      .from("repos")
      .select("config")
      .eq("id", repoId)
      .single();
    if (repoData?.config) {
      repoConfig = repoData.config as Record<string, unknown>;
    }
  }

  // Run the check pipeline
  const startTime = performance.now();
  const pipelineResult = await runCheckPipeline({
    files,
    commits,
    branch,
    repoFullName,
    config: repoConfig,
  });
  const duration = Math.round(performance.now() - startTime);
  console.log(`[webhook] Pipeline completed in ${duration}ms — ${pipelineResult.checks.length} checks, failures=${pipelineResult.failureCount}, warnings=${pipelineResult.warningCount}`);

  // Determine GitHub conclusion
  const conclusion = pipelineResult.hasFailures
    ? "failure"
    : pipelineResult.hasWarnings
      ? "neutral"
      : "success";

  // Update GitHub Check Run with results
  await updateCheckRun({
    installationId,
    owner: repoOwner,
    repo: repoName,
    checkRunId: checkRun.id,
    status: "completed",
    conclusion,
    output: {
      title: pipelineResult.hasFailures
        ? `${pipelineResult.failureCount} check(s) failed`
        : pipelineResult.hasWarnings
          ? `${pipelineResult.warningCount} warning(s)`
          : "All checks passed",
      summary: pipelineResult.summary,
      annotations: pipelineResult.annotations.slice(0, 50), // GitHub limits to 50
    },
  });

  // Store individual check results in Supabase
  if (checkRunRecord) {
    const checkResults = pipelineResult.checks.map((check) => ({
      check_run_id: checkRunRecord.id,
      check_type: check.type,
      status: check.status,
      title: check.title,
      summary: check.summary || null,
      details: check.details || {},
      duration_ms: check.duration_ms || null,
    }));

    if (checkResults.length > 0) {
      await supabase.from("check_results").insert(checkResults);
    }

    // Update check_runs record with totals
    const passed = pipelineResult.checks.filter(
      (c) => c.status === "pass"
    ).length;
    const failed = pipelineResult.checks.filter(
      (c) => c.status === "fail"
    ).length;
    const warned = pipelineResult.checks.filter(
      (c) => c.status === "warn"
    ).length;

    await supabase
      .from("check_runs")
      .update({
        status: pipelineResult.hasFailures
          ? "failed"
          : pipelineResult.hasWarnings
            ? "warned"
            : "passed",
        completed_at: new Date().toISOString(),
        total_checks: pipelineResult.checks.length,
        passed_checks: passed,
        failed_checks: failed,
        warned_checks: warned,
      })
      .eq("id", checkRunRecord.id);
  }

  // Post PR comment with full report (auto-feedback)
  const dashboardUrl = process.env.NEXT_PUBLIC_APP_URL || "https://lastgate.dev";
  const comment = buildPRComment(pipelineResult, `${dashboardUrl}/review/${checkRunRecord?.id}`);

  // Find PR associated with this branch
  let targetPrNumber = prNumber;
  if (!targetPrNumber && event === "push") {
    try {
      const prs = await octokit.request("GET /repos/{owner}/{repo}/pulls", {
        owner: repoOwner,
        repo: repoName,
        head: `${repoOwner}:${branch}`,
        state: "open",
      });
      if (prs.data.length > 0) {
        targetPrNumber = (prs.data[0] as Record<string, unknown>).number as number;
      }
    } catch (err) {
      console.error("[webhook] Failed to find PR for branch:", err);
    }
  }

  if (targetPrNumber) {
    try {
      // Check if LastGate already has a comment on this PR
      const existingComments = await octokit.request(
        "GET /repos/{owner}/{repo}/issues/{issue_number}/comments",
        { owner: repoOwner, repo: repoName, issue_number: targetPrNumber }
      );
      const lastgateComment = (existingComments.data as Array<Record<string, unknown>>).find(
        (c) => (c.body as string)?.includes("🛡 LastGate Pre-flight Report")
      );

      if (lastgateComment) {
        // UPDATE existing comment (don't spam with new ones)
        await octokit.request(
          "PATCH /repos/{owner}/{repo}/issues/comments/{comment_id}",
          {
            owner: repoOwner,
            repo: repoName,
            comment_id: lastgateComment.id as number,
            body: comment,
          }
        );
        console.log(`[webhook] Updated existing PR comment on #${targetPrNumber}`);
      } else {
        // CREATE new comment
        await octokit.request(
          "POST /repos/{owner}/{repo}/issues/{issue_number}/comments",
          {
            owner: repoOwner,
            repo: repoName,
            issue_number: targetPrNumber,
            body: comment,
          }
        );
        console.log(`[webhook] Created new PR comment on #${targetPrNumber}`);
      }
    } catch (err) {
      console.error("[webhook] Failed to post PR comment:", err);
    }
  }

  // Direct push protection
  const protectedBranches = (repoConfig as Record<string, unknown>)?.protected_branches as string[] | undefined;
  const isProtectedBranch = protectedBranches?.includes(branch) || branch === "main" || branch === "master";

  if (event === "push" && isProtectedBranch && pipelineResult.hasFailures) {
    // Post warning comment on the commit itself
    const warningBody = buildDirectPushWarning(branch, pipelineResult);
    await postCommitComment(octokit, repoOwner, repoName, headSha, warningBody);

    // Send urgent notification
    await dispatchNotification(repoId, pipelineResult, { urgent: true });

    console.log(`[webhook] Direct push to protected branch ${branch} with failures — posted warning`);
  }

  return NextResponse.json({
    ok: true,
    checkRunId: checkRun.id,
    conclusion,
    checks: pipelineResult.checks.length,
    duration,
  });
}
