import { NextRequest, NextResponse } from "next/server";
import { verifyWebhookSignature } from "@/lib/github/webhooks";
import { createCheckRun, updateCheckRun } from "@/lib/github/checks";
import { getInstallationOctokit } from "@/lib/github/app";
import { createServerSupabaseClient } from "@/lib/supabase/server";
import { runCheckPipeline } from "@lastgate/engine";
import type { ChangedFile, CommitInfo } from "@lastgate/engine";

async function fetchChangedFiles(
  octokit: Awaited<ReturnType<typeof getInstallationOctokit>>,
  owner: string,
  repo: string,
  sha: string
): Promise<ChangedFile[]> {
  try {
    const { data } = await octokit.request(
      "GET /repos/{owner}/{repo}/commits/{ref}",
      { owner, repo, ref: sha }
    );

    return (data.files || []).map((f: Record<string, unknown>) => ({
      path: f.filename as string,
      content: (f.patch as string) || "",
      patch: (f.patch as string) || "",
      status: mapGitHubStatus(f.status as string),
    }));
  } catch (error) {
    console.error("Failed to fetch changed files:", error);
    return [];
  }
}

function mapGitHubStatus(
  status: string
): "added" | "modified" | "removed" | "renamed" {
  switch (status) {
    case "added":
      return "added";
    case "removed":
      return "removed";
    case "renamed":
      return "renamed";
    default:
      return "modified";
  }
}

async function findOrCreateRepo(
  supabase: ReturnType<typeof createServerSupabaseClient>,
  repoFullName: string,
  installationId: number
) {
  // Try to find existing repo
  const { data: existing } = await supabase
    .from("repos")
    .select("id")
    .eq("full_name", repoFullName)
    .single();

  if (existing) return existing.id;

  // Create repo record
  const { data: created } = await supabase
    .from("repos")
    .insert({
      full_name: repoFullName,
      github_repo_id: 0, // Will be updated on next sync
      installation_id: installationId,
      default_branch: "main",
    })
    .select("id")
    .single();

  return created?.id || null;
}

function detectAgentCommit(message: string, author: string): boolean {
  const agentPatterns = [
    /\b(claude|copilot|cursor|aider|cody|devin|sweep)\b/i,
    /\bgenerated by\b/i,
    /\bauto-generated\b/i,
    /\bai-generated\b/i,
  ];
  const text = `${message} ${author}`;
  return agentPatterns.some((p) => p.test(text));
}

export async function POST(request: NextRequest) {
  try {
    const body = await request.text();
    const signature = request.headers.get("x-hub-signature-256");

    if (!signature) {
      return NextResponse.json(
        { error: "Missing signature" },
        { status: 401 }
      );
    }

    const secret = process.env.GITHUB_WEBHOOK_SECRET;
    if (!secret) {
      return NextResponse.json(
        { error: "Webhook secret not configured" },
        { status: 500 }
      );
    }

    const isValid = verifyWebhookSignature(body, signature, secret);
    if (!isValid) {
      return NextResponse.json(
        { error: "Invalid signature" },
        { status: 401 }
      );
    }

    const event = request.headers.get("x-github-event");
    const payload = JSON.parse(body);
    const supabase = createServerSupabaseClient();

    if (event === "push" || event === "pull_request") {
      return await handleCheckEvent(event, payload, supabase);
    }

    // Acknowledge unhandled events
    return NextResponse.json({ ok: true, event, action: "ignored" });
  } catch (error) {
    console.error("Webhook error:", error);
    return NextResponse.json(
      { error: "Internal server error" },
      { status: 500 }
    );
  }
}

async function handleCheckEvent(
  event: string,
  payload: Record<string, unknown>,
  supabase: ReturnType<typeof createServerSupabaseClient>
) {
  const installationId = (
    payload.installation as Record<string, unknown> | undefined
  )?.id as number | undefined;

  if (!installationId) {
    return NextResponse.json(
      { error: "No installation ID" },
      { status: 400 }
    );
  }

  // Extract event-specific data
  const repository = payload.repository as Record<string, unknown>;
  const repoOwner = (repository.owner as Record<string, unknown>)
    .login as string;
  const repoName = repository.name as string;
  const repoFullName = repository.full_name as string;

  let headSha: string;
  let branch: string;
  let commitMessage: string;
  let commitAuthor: string;
  let prNumber: number | null = null;
  let triggerEvent: string;

  if (event === "push") {
    headSha = payload.after as string;
    branch = (payload.ref as string).replace("refs/heads/", "");
    const headCommit = payload.head_commit as Record<string, unknown> | null;
    commitMessage = (headCommit?.message as string) || "";
    commitAuthor = (payload.pusher as Record<string, unknown>).name as string;
    triggerEvent = "push";
  } else {
    const action = payload.action as string;
    if (action !== "opened" && action !== "synchronize") {
      return NextResponse.json({ ok: true, action: "ignored" });
    }
    const pr = payload.pull_request as Record<string, unknown>;
    const head = pr.head as Record<string, unknown>;
    headSha = head.sha as string;
    branch = head.ref as string;
    commitMessage = pr.title as string;
    commitAuthor = (pr.user as Record<string, unknown>).login as string;
    prNumber = pr.number as number;
    triggerEvent = "pull_request";
  }

  const octokit = await getInstallationOctokit(installationId);

  // Create a GitHub Check Run
  const checkRun = await createCheckRun({
    installationId,
    owner: repoOwner,
    repo: repoName,
    headSha,
    name: "LastGate Check Pipeline",
  });

  // Find or create repo record in Supabase
  const repoId = await findOrCreateRepo(supabase, repoFullName, installationId);

  // Insert check_runs record
  const { data: checkRunRecord } = await supabase
    .from("check_runs")
    .insert({
      repo_id: repoId,
      commit_sha: headSha,
      pr_number: prNumber,
      branch,
      trigger_event: triggerEvent,
      status: "running",
      commit_message: commitMessage,
      commit_author: commitAuthor,
      is_agent_commit: detectAgentCommit(commitMessage, commitAuthor),
    })
    .select("id")
    .single();

  // Fetch changed files from GitHub
  const files = await fetchChangedFiles(octokit, repoOwner, repoName, headSha);

  // Build commit info
  const commits: CommitInfo[] = [
    {
      sha: headSha,
      message: commitMessage,
      author: commitAuthor,
      timestamp: new Date().toISOString(),
    },
  ];

  // Fetch repo config if available
  let repoConfig = {};
  if (repoId) {
    const { data: repoData } = await supabase
      .from("repos")
      .select("config")
      .eq("id", repoId)
      .single();
    if (repoData?.config) {
      repoConfig = repoData.config as Record<string, unknown>;
    }
  }

  // Run the check pipeline
  const startTime = performance.now();
  const pipelineResult = await runCheckPipeline({
    files,
    commits,
    branch,
    repoFullName,
    config: repoConfig,
  });
  const duration = Math.round(performance.now() - startTime);

  // Determine GitHub conclusion
  const conclusion = pipelineResult.hasFailures
    ? "failure"
    : pipelineResult.hasWarnings
      ? "neutral"
      : "success";

  // Update GitHub Check Run with results
  await updateCheckRun({
    installationId,
    owner: repoOwner,
    repo: repoName,
    checkRunId: checkRun.id,
    status: "completed",
    conclusion,
    output: {
      title: pipelineResult.hasFailures
        ? `${pipelineResult.failureCount} check(s) failed`
        : pipelineResult.hasWarnings
          ? `${pipelineResult.warningCount} warning(s)`
          : "All checks passed",
      summary: pipelineResult.summary,
      annotations: pipelineResult.annotations.slice(0, 50), // GitHub limits to 50
    },
  });

  // Store individual check results in Supabase
  if (checkRunRecord) {
    const checkResults = pipelineResult.checks.map((check) => ({
      check_run_id: checkRunRecord.id,
      check_type: check.type,
      status: check.status,
      title: check.title,
      summary: check.summary || null,
      details: check.details || {},
      duration_ms: check.duration_ms || null,
    }));

    if (checkResults.length > 0) {
      await supabase.from("check_results").insert(checkResults);
    }

    // Update check_runs record with totals
    const passed = pipelineResult.checks.filter(
      (c) => c.status === "pass"
    ).length;
    const failed = pipelineResult.checks.filter(
      (c) => c.status === "fail"
    ).length;
    const warned = pipelineResult.checks.filter(
      (c) => c.status === "warn"
    ).length;

    await supabase
      .from("check_runs")
      .update({
        status: pipelineResult.hasFailures
          ? "failed"
          : pipelineResult.hasWarnings
            ? "warned"
            : "passed",
        completed_at: new Date().toISOString(),
        total_checks: pipelineResult.checks.length,
        passed_checks: passed,
        failed_checks: failed,
        warned_checks: warned,
      })
      .eq("id", checkRunRecord.id);
  }

  return NextResponse.json({
    ok: true,
    checkRunId: checkRun.id,
    conclusion,
    checks: pipelineResult.checks.length,
    duration,
  });
}
